//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiStoreWithMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DigiStoreDBModelContainer : DbContext
    {
        public DigiStoreDBModelContainer()
            : base("name=DigiStoreDBModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<StoreHours> StoreHours { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
    }
}
