// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace DigistoreTesting
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Create Valid Test User using Web UI
        /// </summary>
        public void CreateValidTestUser()
        {
            #region Variable Declarations
            BrowserWindow uIHomeInternetExplorerWindow = this.UIHomeInternetExplorerWindow;
            HtmlHyperlink uILogInHyperlink = this.UIHomeInternetExplorerWindow.UIHomeDocument.UILogInHyperlink;
            HtmlHyperlink uISignupHyperlink = this.UIHomeInternetExplorerWindow.UILoginDocument.UISignupHyperlink;
            HtmlEdit uIUsernameEdit = this.UIHomeInternetExplorerWindow.UIRegisterDocument.UIUsernameEdit;
            HtmlHyperlink uICheckUsernameHyperlink = this.UIHomeInternetExplorerWindow.UIRegisterDocument.UICheckUsernameHyperlink;
            HtmlEdit uIPasswordEdit = this.UIHomeInternetExplorerWindow.UIRegisterDocument.UIPasswordEdit;
            HtmlEdit uIConfirmpasswordEdit = this.UIHomeInternetExplorerWindow.UIRegisterDocument.UIConfirmpasswordEdit;
            HtmlEdit uIFirstNameEdit = this.UIHomeInternetExplorerWindow.UIRegisterDocument.UIFirstNameEdit;
            HtmlEdit uILastNameEdit = this.UIHomeInternetExplorerWindow.UIRegisterDocument.UILastNameEdit;
            HtmlEdit uIEmailEdit = this.UIHomeInternetExplorerWindow.UIRegisterDocument.UIEmailEdit;
            HtmlEdit uIItemEdit = this.UIHomeInternetExplorerWindow.UIRegisterDocument.UIItemEdit;
            HtmlSpan uICanadaPane = this.UIHomeInternetExplorerWindow.UIRegisterDocument.UISelectoptions16cd832Custom.UICanadaPane;
            HtmlDiv uIAfghanistanAlbaniaAlPane = this.UIHomeInternetExplorerWindow.UIRegisterDocument.UIAfghanistanAlbaniaAlPane;
            HtmlEdit uITownCityEdit = this.UIHomeInternetExplorerWindow.UIRegisterDocument.UITownCityEdit;
            HtmlEdit uIProvinceStateEdit = this.UIHomeInternetExplorerWindow.UIRegisterDocument.UIProvinceStateEdit;
            HtmlEdit uIPostalZipCodeEdit = this.UIHomeInternetExplorerWindow.UIRegisterDocument.UIPostalZipCodeEdit;
            HtmlEdit uIAddressEdit = this.UIHomeInternetExplorerWindow.UIRegisterDocument.UIAddressEdit;
            HtmlEdit uIPhoneNumberEdit = this.UIHomeInternetExplorerWindow.UIRegisterDocument.UIPhoneNumberEdit;
            HtmlInputButton uISignupButton = this.UIHomeInternetExplorerWindow.UIRegisterDocument.UISignupButton;
            #endregion

            // Go to web page 'http://localhost:50221/'
            uIHomeInternetExplorerWindow.NavigateToUrl(new System.Uri(this.CreateValidTestUserParams.UIHomeInternetExplorerWindowUrl));

            // Click 'Log In' link
            Mouse.Click(uILogInHyperlink, new Point(53, 28));

            // Click 'Sign up!' link
            Mouse.Click(uISignupHyperlink, new Point(616, 29));

            // Type 'TestUser2' in 'Username' text box
            uIUsernameEdit.Text = this.CreateValidTestUserParams.UIUsernameEditText;

            // Type '{Tab}' in 'Username' text box
            Keyboard.SendKeys(uIUsernameEdit, this.CreateValidTestUserParams.UIUsernameEditSendKeys, ModifierKeys.None);

            // Type '{Tab}' in 'Check Username' link
            Keyboard.SendKeys(uICheckUsernameHyperlink, this.CreateValidTestUserParams.UICheckUsernameHyperlinkSendKeys, ModifierKeys.None);

            // Type '********' in 'Password' text box
            uIPasswordEdit.Password = this.CreateValidTestUserParams.UIPasswordEditPassword;

            // Type '{Tab}' in 'Password' text box
            Keyboard.SendKeys(uIPasswordEdit, this.CreateValidTestUserParams.UIPasswordEditSendKeys, ModifierKeys.None);

            // Type '********' in 'Confirm password' text box
            uIConfirmpasswordEdit.Password = this.CreateValidTestUserParams.UIConfirmpasswordEditPassword;

            // Type '{Tab}' in 'Confirm password' text box
            Keyboard.SendKeys(uIConfirmpasswordEdit, this.CreateValidTestUserParams.UIConfirmpasswordEditSendKeys, ModifierKeys.None);

            // Type 'Test' in 'First Name' text box
            uIFirstNameEdit.Text = this.CreateValidTestUserParams.UIFirstNameEditText;

            // Type '{Tab}' in 'First Name' text box
            Keyboard.SendKeys(uIFirstNameEdit, this.CreateValidTestUserParams.UIFirstNameEditSendKeys, ModifierKeys.None);

            // Type 'User2' in 'Last Name' text box
            uILastNameEdit.Text = this.CreateValidTestUserParams.UILastNameEditText;

            // Type '{Tab}' in 'Last Name' text box
            Keyboard.SendKeys(uILastNameEdit, this.CreateValidTestUserParams.UILastNameEditSendKeys, ModifierKeys.None);

            // Type 'testuser2@email.com' in 'Email' text box
            uIEmailEdit.Text = this.CreateValidTestUserParams.UIEmailEditText;

            // Type '{Tab}' in 'Email' text box
            Keyboard.SendKeys(uIEmailEdit, this.CreateValidTestUserParams.UIEmailEditSendKeys, ModifierKeys.None);

            // Type 'can' in text box
            Keyboard.SendKeys(uIItemEdit, this.CreateValidTestUserParams.UIItemEditSendKeys, ModifierKeys.None);

            // Click 'Canada' pane
            Mouse.Click(uICanadaPane, new Point(137, 20));

            // Type '{Tab}' in '▼ Afghanistan Albania Algeria' pane
            Keyboard.SendKeys(uIAfghanistanAlbaniaAlPane, this.CreateValidTestUserParams.UIAfghanistanAlbaniaAlPaneSendKeys, ModifierKeys.None);

            // Type '{Tab}' in text box
            Keyboard.SendKeys(uIItemEdit, this.CreateValidTestUserParams.UIItemEditSendKeys1, ModifierKeys.None);

            // Type 'Brampton' in 'Town/City' text box
            uITownCityEdit.Text = this.CreateValidTestUserParams.UITownCityEditText;

            // Type '{Tab}' in 'Town/City' text box
            Keyboard.SendKeys(uITownCityEdit, this.CreateValidTestUserParams.UITownCityEditSendKeys, ModifierKeys.None);

            // Type 'Ontario' in 'Province/State' text box
            uIProvinceStateEdit.Text = this.CreateValidTestUserParams.UIProvinceStateEditText;

            // Type '{Tab}' in 'Province/State' text box
            Keyboard.SendKeys(uIProvinceStateEdit, this.CreateValidTestUserParams.UIProvinceStateEditSendKeys, ModifierKeys.None);

            // Type 'L6V 3J8' in 'Postal/Zip Code' text box
            uIPostalZipCodeEdit.Text = this.CreateValidTestUserParams.UIPostalZipCodeEditText;

            // Type '{Tab}' in 'Postal/Zip Code' text box
            Keyboard.SendKeys(uIPostalZipCodeEdit, this.CreateValidTestUserParams.UIPostalZipCodeEditSendKeys, ModifierKeys.None);

            // Type '112 Royal Salisbury Way' in 'Address' text box
            uIAddressEdit.Text = this.CreateValidTestUserParams.UIAddressEditText;

            // Type '{Tab}' in 'Address' text box
            Keyboard.SendKeys(uIAddressEdit, this.CreateValidTestUserParams.UIAddressEditSendKeys, ModifierKeys.None);

            // Type '905 455 1121' in 'Phone Number' text box
            uIPhoneNumberEdit.Text = this.CreateValidTestUserParams.UIPhoneNumberEditText;

            // Type '{Tab}' in 'Phone Number' text box
            Keyboard.SendKeys(uIPhoneNumberEdit, this.CreateValidTestUserParams.UIPhoneNumberEditSendKeys, ModifierKeys.None);

            // Type '{Enter}' in 'Sign up' button
            Keyboard.SendKeys(uISignupButton, this.CreateValidTestUserParams.UISignupButtonSendKeys, ModifierKeys.None);
        }
        
        #region Properties
        public virtual CreateValidTestUserParams CreateValidTestUserParams
        {
            get
            {
                if ((this.mCreateValidTestUserParams == null))
                {
                    this.mCreateValidTestUserParams = new CreateValidTestUserParams();
                }
                return this.mCreateValidTestUserParams;
            }
        }
        
        public UIHomeInternetExplorerWindow UIHomeInternetExplorerWindow
        {
            get
            {
                if ((this.mUIHomeInternetExplorerWindow == null))
                {
                    this.mUIHomeInternetExplorerWindow = new UIHomeInternetExplorerWindow();
                }
                return this.mUIHomeInternetExplorerWindow;
            }
        }
        #endregion
        
        #region Fields
        private CreateValidTestUserParams mCreateValidTestUserParams;
        
        private UIHomeInternetExplorerWindow mUIHomeInternetExplorerWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'CreateValidTestUser'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class CreateValidTestUserParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://localhost:50221/'
        /// </summary>
        public string UIHomeInternetExplorerWindowUrl = "http://localhost:50221/";
        
        /// <summary>
        /// Type 'TestUser2' in 'Username' text box
        /// </summary>
        public string UIUsernameEditText = "TestUser5";
        
        /// <summary>
        /// Type '{Tab}' in 'Username' text box
        /// </summary>
        public string UIUsernameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '{Tab}' in 'Check Username' link
        /// </summary>
        public string UICheckUsernameHyperlinkSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditPassword = "mBQq9cL71wNvIwXGUwEmyWZDD3mxe3wd";
        
        /// <summary>
        /// Type '{Tab}' in 'Password' text box
        /// </summary>
        public string UIPasswordEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'Confirm password' text box
        /// </summary>
        public string UIConfirmpasswordEditPassword = "mBQq9cL71wNvIwXGUwEmyWZDD3mxe3wd";
        
        /// <summary>
        /// Type '{Tab}' in 'Confirm password' text box
        /// </summary>
        public string UIConfirmpasswordEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'Test' in 'First Name' text box
        /// </summary>
        public string UIFirstNameEditText = "Test";
        
        /// <summary>
        /// Type '{Tab}' in 'First Name' text box
        /// </summary>
        public string UIFirstNameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'User2' in 'Last Name' text box
        /// </summary>
        public string UILastNameEditText = "User2";
        
        /// <summary>
        /// Type '{Tab}' in 'Last Name' text box
        /// </summary>
        public string UILastNameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'testuser2@email.com' in 'Email' text box
        /// </summary>
        public string UIEmailEditText = "testuser5@email.com";
        
        /// <summary>
        /// Type '{Tab}' in 'Email' text box
        /// </summary>
        public string UIEmailEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'can' in text box
        /// </summary>
        public string UIItemEditSendKeys = "can";
        
        /// <summary>
        /// Type '{Tab}' in '▼ Afghanistan Albania Algeria' pane
        /// </summary>
        public string UIAfghanistanAlbaniaAlPaneSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '{Tab}' in text box
        /// </summary>
        public string UIItemEditSendKeys1 = "{Tab}";
        
        /// <summary>
        /// Type 'Brampton' in 'Town/City' text box
        /// </summary>
        public string UITownCityEditText = "Brampton";
        
        /// <summary>
        /// Type '{Tab}' in 'Town/City' text box
        /// </summary>
        public string UITownCityEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'Ontario' in 'Province/State' text box
        /// </summary>
        public string UIProvinceStateEditText = "Ontario";
        
        /// <summary>
        /// Type '{Tab}' in 'Province/State' text box
        /// </summary>
        public string UIProvinceStateEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'L6V 3J8' in 'Postal/Zip Code' text box
        /// </summary>
        public string UIPostalZipCodeEditText = "L6V 3J8";
        
        /// <summary>
        /// Type '{Tab}' in 'Postal/Zip Code' text box
        /// </summary>
        public string UIPostalZipCodeEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '112 Royal Salisbury Way' in 'Address' text box
        /// </summary>
        public string UIAddressEditText = "112 Royal Salisbury Way";
        
        /// <summary>
        /// Type '{Tab}' in 'Address' text box
        /// </summary>
        public string UIAddressEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '905 455 1121' in 'Phone Number' text box
        /// </summary>
        public string UIPhoneNumberEditText = "905 455 1121";
        
        /// <summary>
        /// Type '{Tab}' in 'Phone Number' text box
        /// </summary>
        public string UIPhoneNumberEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '{Enter}' in 'Sign up' button
        /// </summary>
        public string UISignupButtonSendKeys = "{Enter}";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIHomeInternetExplorerWindow : BrowserWindow
    {
        
        public UIHomeInternetExplorerWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Home";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Home");
            this.WindowTitles.Add("Log in");
            this.WindowTitles.Add("Register");
            this.WindowTitles.Add("New tab");
            this.WindowTitles.Add("Blank Page");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHomeDocument UIHomeDocument
        {
            get
            {
                if ((this.mUIHomeDocument == null))
                {
                    this.mUIHomeDocument = new UIHomeDocument(this);
                }
                return this.mUIHomeDocument;
            }
        }
        
        public UILoginDocument UILoginDocument
        {
            get
            {
                if ((this.mUILoginDocument == null))
                {
                    this.mUILoginDocument = new UILoginDocument(this);
                }
                return this.mUILoginDocument;
            }
        }
        
        public UIRegisterDocument UIRegisterDocument
        {
            get
            {
                if ((this.mUIRegisterDocument == null))
                {
                    this.mUIRegisterDocument = new UIRegisterDocument(this);
                }
                return this.mUIRegisterDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIHomeDocument mUIHomeDocument;
        
        private UILoginDocument mUILoginDocument;
        
        private UIRegisterDocument mUIRegisterDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIHomeDocument : HtmlDocument
    {
        
        public UIHomeDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Home";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:50221/";
            this.WindowTitles.Add("Home");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UILogInHyperlink
        {
            get
            {
                if ((this.mUILogInHyperlink == null))
                {
                    this.mUILogInHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUILogInHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUILogInHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUILogInHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUILogInHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Log In";
                    this.mUILogInHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Account/Login";
                    this.mUILogInHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUILogInHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:50221/Account/Login";
                    this.mUILogInHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "yellow-text accent-3";
                    this.mUILogInHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"yellow-text accent-3\" href=\"/Acco";
                    this.mUILogInHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "4";
                    this.mUILogInHyperlink.WindowTitles.Add("Home");
                    #endregion
                }
                return this.mUILogInHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUILogInHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UILoginDocument : HtmlDocument
    {
        
        public UILoginDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Log in";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Account/Login";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:50221/Account/Login";
            this.WindowTitles.Add("Log in");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UISignupHyperlink
        {
            get
            {
                if ((this.mUISignupHyperlink == null))
                {
                    this.mUISignupHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUISignupHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUISignupHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUISignupHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUISignupHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Sign up!";
                    this.mUISignupHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Account/Register";
                    this.mUISignupHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUISignupHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:50221/Account/Register";
                    this.mUISignupHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "btn waves-light blue darken-3 yellow-text accent-3 truncate";
                    this.mUISignupHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"btn waves-light blue darken-3 yel";
                    this.mUISignupHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "10";
                    this.mUISignupHyperlink.WindowTitles.Add("Log in");
                    #endregion
                }
                return this.mUISignupHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUISignupHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIRegisterDocument : HtmlDocument
    {
        
        public UIRegisterDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Register";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Account/Register";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:50221/Account/Register";
            this.WindowTitles.Add("Register");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIUsernameEdit
        {
            get
            {
                if ((this.mUIUsernameEdit == null))
                {
                    this.mUIUsernameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIUsernameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Username";
                    this.mUIUsernameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Username";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Username";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "text-box single-line";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Username\" class=\"text-box single-l";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIUsernameEdit.WindowTitles.Add("Register");
                    #endregion
                }
                return this.mUIUsernameEdit;
            }
        }
        
        public HtmlHyperlink UICheckUsernameHyperlink
        {
            get
            {
                if ((this.mUICheckUsernameHyperlink == null))
                {
                    this.mUICheckUsernameHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUICheckUsernameHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "checkUsername";
                    this.mUICheckUsernameHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUICheckUsernameHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUICheckUsernameHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Check Username";
                    this.mUICheckUsernameHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Account/Register";
                    this.mUICheckUsernameHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUICheckUsernameHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:50221/Account/Register";
                    this.mUICheckUsernameHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "btn btn-large waves-effect blue darken-3 yellow-text accent-3";
                    this.mUICheckUsernameHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"btn btn-large waves-effect blue d";
                    this.mUICheckUsernameHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "11";
                    this.mUICheckUsernameHyperlink.WindowTitles.Add("Register");
                    #endregion
                }
                return this.mUICheckUsernameHyperlink;
            }
        }
        
        public HtmlEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Password";
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "text-box single-line password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Password\" class=\"text-box single-l";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUIPasswordEdit.WindowTitles.Add("Register");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        
        public HtmlEdit UIConfirmpasswordEdit
        {
            get
            {
                if ((this.mUIConfirmpasswordEdit == null))
                {
                    this.mUIConfirmpasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIConfirmpasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "ConfirmPassword";
                    this.mUIConfirmpasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "ConfirmPassword";
                    this.mUIConfirmpasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Confirm password";
                    this.mUIConfirmpasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIConfirmpasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIConfirmpasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "text-box single-line password";
                    this.mUIConfirmpasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"ConfirmPassword\" class=\"text-box s";
                    this.mUIConfirmpasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "4";
                    this.mUIConfirmpasswordEdit.WindowTitles.Add("Register");
                    #endregion
                }
                return this.mUIConfirmpasswordEdit;
            }
        }
        
        public HtmlEdit UIFirstNameEdit
        {
            get
            {
                if ((this.mUIFirstNameEdit == null))
                {
                    this.mUIFirstNameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIFirstNameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "FirstName";
                    this.mUIFirstNameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "FirstName";
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "First Name";
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "text-box single-line";
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"FirstName\" class=\"text-box single-";
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "5";
                    this.mUIFirstNameEdit.WindowTitles.Add("Register");
                    #endregion
                }
                return this.mUIFirstNameEdit;
            }
        }
        
        public HtmlEdit UILastNameEdit
        {
            get
            {
                if ((this.mUILastNameEdit == null))
                {
                    this.mUILastNameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUILastNameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "LastName";
                    this.mUILastNameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "LastName";
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Last Name";
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "text-box single-line";
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"LastName\" class=\"text-box single-l";
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "6";
                    this.mUILastNameEdit.WindowTitles.Add("Register");
                    #endregion
                }
                return this.mUILastNameEdit;
            }
        }
        
        public HtmlEdit UIEmailEdit
        {
            get
            {
                if ((this.mUIEmailEdit == null))
                {
                    this.mUIEmailEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIEmailEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Email";
                    this.mUIEmailEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Email";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Email";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "text-box single-line";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Email\" class=\"text-box single-line";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "7";
                    this.mUIEmailEdit.WindowTitles.Add("Register");
                    #endregion
                }
                return this.mUIEmailEdit;
            }
        }
        
        public UISelectoptions565d02dCustom UISelectoptions565d02dCustom
        {
            get
            {
                if ((this.mUISelectoptions565d02dCustom == null))
                {
                    this.mUISelectoptions565d02dCustom = new UISelectoptions565d02dCustom(this);
                }
                return this.mUISelectoptions565d02dCustom;
            }
        }
        
        public HtmlEdit UITownCityEdit
        {
            get
            {
                if ((this.mUITownCityEdit == null))
                {
                    this.mUITownCityEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUITownCityEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "City";
                    this.mUITownCityEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "City";
                    this.mUITownCityEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Town/City";
                    this.mUITownCityEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUITownCityEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUITownCityEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "text-box single-line";
                    this.mUITownCityEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"City\" class=\"text-box single-line\"";
                    this.mUITownCityEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "9";
                    this.mUITownCityEdit.WindowTitles.Add("Register");
                    #endregion
                }
                return this.mUITownCityEdit;
            }
        }
        
        public HtmlEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mUIItemEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = null;
                    this.mUIItemEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIItemEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIItemEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIItemEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "select-dropdown active";
                    this.mUIItemEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "class=\"select-dropdown active\" type=\"tex";
                    this.mUIItemEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "8";
                    this.mUIItemEdit.WindowTitles.Add("Register");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        
        public HtmlEdit UIProvinceStateEdit
        {
            get
            {
                if ((this.mUIProvinceStateEdit == null))
                {
                    this.mUIProvinceStateEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIProvinceStateEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Province";
                    this.mUIProvinceStateEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Province";
                    this.mUIProvinceStateEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Province/State";
                    this.mUIProvinceStateEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIProvinceStateEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIProvinceStateEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "text-box single-line";
                    this.mUIProvinceStateEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Province\" class=\"text-box single-l";
                    this.mUIProvinceStateEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "10";
                    this.mUIProvinceStateEdit.WindowTitles.Add("Register");
                    #endregion
                }
                return this.mUIProvinceStateEdit;
            }
        }
        
        public HtmlEdit UIPostalZipCodeEdit
        {
            get
            {
                if ((this.mUIPostalZipCodeEdit == null))
                {
                    this.mUIPostalZipCodeEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPostalZipCodeEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "PostalCode";
                    this.mUIPostalZipCodeEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "PostalCode";
                    this.mUIPostalZipCodeEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Postal/Zip Code";
                    this.mUIPostalZipCodeEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIPostalZipCodeEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPostalZipCodeEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "text-box single-line";
                    this.mUIPostalZipCodeEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"PostalCode\" class=\"text-box single";
                    this.mUIPostalZipCodeEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "11";
                    this.mUIPostalZipCodeEdit.WindowTitles.Add("Register");
                    #endregion
                }
                return this.mUIPostalZipCodeEdit;
            }
        }
        
        public HtmlEdit UIAddressEdit
        {
            get
            {
                if ((this.mUIAddressEdit == null))
                {
                    this.mUIAddressEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIAddressEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Street";
                    this.mUIAddressEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Street";
                    this.mUIAddressEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Address";
                    this.mUIAddressEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIAddressEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIAddressEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "text-box single-line";
                    this.mUIAddressEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Street\" class=\"text-box single-lin";
                    this.mUIAddressEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "12";
                    this.mUIAddressEdit.WindowTitles.Add("Register");
                    #endregion
                }
                return this.mUIAddressEdit;
            }
        }
        
        public HtmlEdit UIPhoneNumberEdit
        {
            get
            {
                if ((this.mUIPhoneNumberEdit == null))
                {
                    this.mUIPhoneNumberEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPhoneNumberEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "PhoneNumber";
                    this.mUIPhoneNumberEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "PhoneNumber";
                    this.mUIPhoneNumberEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Phone Number";
                    this.mUIPhoneNumberEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIPhoneNumberEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPhoneNumberEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "text-box single-line";
                    this.mUIPhoneNumberEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"PhoneNumber\" class=\"text-box singl";
                    this.mUIPhoneNumberEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "13";
                    this.mUIPhoneNumberEdit.WindowTitles.Add("Register");
                    #endregion
                }
                return this.mUIPhoneNumberEdit;
            }
        }
        
        public HtmlInputButton UISignupButton
        {
            get
            {
                if ((this.mUISignupButton == null))
                {
                    this.mUISignupButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUISignupButton.SearchProperties[HtmlButton.PropertyNames.Id] = "submitSignup";
                    this.mUISignupButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUISignupButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Sign up";
                    this.mUISignupButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUISignupButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUISignupButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn waves-light blue darken-3 yellow-text accent-3";
                    this.mUISignupButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn waves-light blue darken-3 yel";
                    this.mUISignupButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "14";
                    this.mUISignupButton.WindowTitles.Add("Register");
                    #endregion
                }
                return this.mUISignupButton;
            }
        }
        
        public UISelectoptions16cd832Custom UISelectoptions16cd832Custom
        {
            get
            {
                if ((this.mUISelectoptions16cd832Custom == null))
                {
                    this.mUISelectoptions16cd832Custom = new UISelectoptions16cd832Custom(this);
                }
                return this.mUISelectoptions16cd832Custom;
            }
        }
        
        public HtmlDiv UIAfghanistanAlbaniaAlPane
        {
            get
            {
                if ((this.mUIAfghanistanAlbaniaAlPane == null))
                {
                    this.mUIAfghanistanAlbaniaAlPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIAfghanistanAlbaniaAlPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIAfghanistanAlbaniaAlPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIAfghanistanAlbaniaAlPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "▼\r\nAfghanistan\r\n\r\n\r\nAlbania\r\n\r\n\r\nAlgeria";
                    this.mUIAfghanistanAlbaniaAlPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIAfghanistanAlbaniaAlPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "input-field col s12 l6";
                    this.mUIAfghanistanAlbaniaAlPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"input-field col s12 l6\"";
                    this.mUIAfghanistanAlbaniaAlPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "25";
                    this.mUIAfghanistanAlbaniaAlPane.WindowTitles.Add("Register");
                    #endregion
                }
                return this.mUIAfghanistanAlbaniaAlPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIUsernameEdit;
        
        private HtmlHyperlink mUICheckUsernameHyperlink;
        
        private HtmlEdit mUIPasswordEdit;
        
        private HtmlEdit mUIConfirmpasswordEdit;
        
        private HtmlEdit mUIFirstNameEdit;
        
        private HtmlEdit mUILastNameEdit;
        
        private HtmlEdit mUIEmailEdit;
        
        private UISelectoptions565d02dCustom mUISelectoptions565d02dCustom;
        
        private HtmlEdit mUITownCityEdit;
        
        private HtmlEdit mUIItemEdit;
        
        private HtmlEdit mUIProvinceStateEdit;
        
        private HtmlEdit mUIPostalZipCodeEdit;
        
        private HtmlEdit mUIAddressEdit;
        
        private HtmlEdit mUIPhoneNumberEdit;
        
        private HtmlInputButton mUISignupButton;
        
        private UISelectoptions16cd832Custom mUISelectoptions16cd832Custom;
        
        private HtmlDiv mUIAfghanistanAlbaniaAlPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UISelectoptions565d02dCustom : HtmlCustom
    {
        
        public UISelectoptions565d02dCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "UL";
            this.SearchProperties["Id"] = "select-options-565d02dc-0d88-c35c-f68a-b2237469623a";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = "dropdown-content select-dropdown active";
            this.FilterProperties["ControlDefinition"] = "class=\"dropdown-content select-dropdown ";
            this.FilterProperties["TagInstance"] = "4";
            this.WindowTitles.Add("Register");
            #endregion
        }
        
        #region Properties
        public HtmlSpan UICanadaPane
        {
            get
            {
                if ((this.mUICanadaPane == null))
                {
                    this.mUICanadaPane = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUICanadaPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUICanadaPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUICanadaPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Canada";
                    this.mUICanadaPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUICanadaPane.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUICanadaPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = null;
                    this.mUICanadaPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "39";
                    this.mUICanadaPane.WindowTitles.Add("Register");
                    #endregion
                }
                return this.mUICanadaPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlSpan mUICanadaPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UISelectoptions16cd832Custom : HtmlCustom
    {
        
        public UISelectoptions16cd832Custom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "UL";
            this.SearchProperties["Id"] = "select-options-16cd8326-b30f-b2d1-32f8-248c070a4b27";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = "dropdown-content select-dropdown active";
            this.FilterProperties["ControlDefinition"] = "class=\"dropdown-content select-dropdown ";
            this.FilterProperties["TagInstance"] = "4";
            this.WindowTitles.Add("Register");
            #endregion
        }
        
        #region Properties
        public HtmlSpan UICanadaPane
        {
            get
            {
                if ((this.mUICanadaPane == null))
                {
                    this.mUICanadaPane = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUICanadaPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUICanadaPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUICanadaPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Canada";
                    this.mUICanadaPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUICanadaPane.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUICanadaPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = null;
                    this.mUICanadaPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "39";
                    this.mUICanadaPane.WindowTitles.Add("Register");
                    #endregion
                }
                return this.mUICanadaPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlSpan mUICanadaPane;
        #endregion
    }
}
